version: '2.1'

services:
  api:
    image: api
    build: .
    environment:
      - NODE_ENV=test
      - OMDB_API_KEY=$OMDB_API_KEY
      - REDIS_HOST=redis
      - PGHOST=postgres
      - PGUSER=api
      - PGPASSWORD=api
      - PGDATABASE=tv_ratings
    command:
      yarn test
    expose: 
      - "8001"
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    ports:
      - 6379
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=tv_ratings
    volumes:
       - ./shows.sql:/docker-entrypoint-initdb.d/1-shows.sql 
